# Generated by Django 5.0.14 on 2026-03-01 23:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("mini_insta", "0002_post_photo"),
    ]

    operations = [
        migrations.AddField(
            model_name="photo",
            name="image_file",
            field=models.ImageField(blank=True, null=True, upload_to="photos/"),
        ),
        migrations.AlterField(
            model_name="photo",
            name="image_url",
            field=models.URLField(blank=True, null=True),
        ),
    ]
