# Generated by Django 5.0.14 on 2026-04-30 17:24

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("project", "0002_seed_checkpoint_data"),
    ]

    operations = [
        migrations.AddField(
            model_name="album",
            name="external_cover_url",
            field=models.URLField(blank=True),
        ),
        migrations.AddField(
            model_name="album",
            name="musicbrainz_release_group_mbid",
            field=models.CharField(blank=True, max_length=64),
        ),
        migrations.AddField(
            model_name="listener",
            name="bio",
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name="listener",
            name="profile_image_url",
            field=models.URLField(blank=True),
        ),
        migrations.AddField(
            model_name="listener",
            name="username",
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.CreateModel(
            name="ReviewLike",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "listener",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="liked_reviews",
                        to="project.listener",
                    ),
                ),
                (
                    "review",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="likes",
                        to="project.review",
                    ),
                ),
            ],
            options={
                "unique_together": {("review", "listener")},
            },
        ),
    ]
