# Generated by Django 5.0.14 on 2026-04-30 17:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("project", "0003_album_external_cover_url_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="review",
            name="review_target",
            field=models.CharField(
                choices=[("album", "Album"), ("song", "Song")],
                default="album",
                max_length=10,
            ),
        ),
        migrations.AddField(
            model_name="review",
            name="track_title",
            field=models.CharField(blank=True, max_length=200),
        ),
    ]
