# Generated by Django 5.0.14 on 2026-04-30 23:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("project", "0004_review_review_target_review_track_title"),
    ]

    operations = [
        migrations.AlterField(
            model_name="listener",
            name="profile_image_url",
            field=models.URLField(blank=True, max_length=2000),
        ),
    ]
